### ISSUE TITLE
Dot (.) in the "namespace".

### ISSUE THREAD

**Issue by thoughtAddict** [sformisano/jetrouter#8]
Hello, 

I'm currently looking through the source code but figured I'd ask this here anyway.  (I'll update if I find it).

Can namespace values contain a period (dot) character?

The error I'm receiving when using a namespace of "10.1109":

```
[20-Aug-2018 23:04:00 UTC] PHP Fatal error:  Uncaught exception 'JetRouter\Exception\InvalidRouteException' 
with message ''10.1109/param' is not a valid route path.' in /var/www/html/wp-content/plugins/jetrouter/src/StaticRouteParser.php:35
Stack trace:
#0 /var/www/html/wp-content/plugins/jetrouter/src/DynamicRouteParser.php(82): JetRouter\StaticRouteParser::validateStaticPath('10.1109/param')
#1 /var/www/html/wp-content/plugins/jetrouter/src/DynamicRouteParser.php(217): JetRouter\DynamicRouteParser::validateStaticPathParts('10.1109/{doi}')
#2 /var/www/html/wp-content/plugins/jetrouter/src/RouteParser.php(104): JetRouter\DynamicRouteParser->setPath('10.1109/{doi}')
#3 /var/www/html/wp-content/plugins/jetrouter/src/RouteStore.php(263): JetRouter\RouteParser->__construct('GET', '10.1109/{doi}', 'doiIEEE', Object(Closure))
#4 /var/www/html/wp-content/plugins/jetrouter/src/RouteStore.php(82): JetRouter\RouteStore->addDynamicRoute('GET', '10.1109/{doi}', 'doiIEEE', Object(Closure))
#5 /var/www/html/wp-content/plugins/jetrouter/src/Router.php(117): JetRouter\ in /var/www/html/wp-content/plugins/jetrouter/src/StaticRouteParser.php on line 35
```

This would be for a URL pattern that matches something like:

www.example.com/10.1109/Test.2018.12345

I've attempted to escape the period using a "\", as well as a double "\\", and have looked at other regex mechanisms to escape the dot.   No luck.

Thanks 

Jon

**Comment by thoughtAddict** [comment]
It would appear that I'd just need to add the dot (.) character to the regex "STATIC_ROUTE_PATH_REGEX" const within the "StaticRouteParser" file.

From:
`const STATIC_ROUTE_PATH_REGEX = '~(?!.*(\/)\1)^([a-zA-Za-zA-Z0-9_\-\/])+$~';`

to:
`const STATIC_ROUTE_PATH_REGEX = '~(?!.*(\/)\1)^([a-zA-Za-zA-Z0-9_\.\-\/])+$~';`

Please correct me if I'm wrong, or this is bad practice.  I just noticed that the comment above that const mentions:

```
  /**
   * Parses the route string allowing alphanumeric characters and the
   * "+", "_", "-" and "/" characters
   * it also does not allow consecutive "/" characters
   */
```

Thanks

Jon
